#!/usr/bin/python3
import sys
import argparse
import os


def _safe_open(path, mode):
	base = os.path.realpath(os.getcwd())
	full = os.path.realpath(os.path.abspath(path))
	if not full.startswith(base + os.sep):
		print("Path is outside the allowed directory: " + path)
		sys.exit(2)
	return open(full, mode)


def generate_source(payload, init_delay=2500, loop_count=-1, loop_delay=5000, blink=True):
	head = '''/*
* Sketch generated by duck2spark from Marcus Mengs aka MaMe82
*
*/
#include "DigiKeyboard.h"

'''
	init = '''
void setup()
{
	// initialize the digital pin as an output.
	pinMode(0, OUTPUT); //LED on Model B
	pinMode(1, OUTPUT); //LED on Model A
	DigiKeyboard.delay(%d); //wait %d milliseconds before first run, to give target time to initialize
}

void loop()
{
''' % (init_delay, init_delay)

	body = '''
	//should code be runned in this loop?
	if (i != 0) {
		DigiKeyboard.sendKeyStroke(0);

		//parse raw duckencoder script
		for (int i=0; i<DUCK_LEN; i+=2)
		{
			uint8_t key = pgm_read_word_near(duckraw + i);
			uint8_t mod = pgm_read_word_near(duckraw + i+1);
			if (key == 0) //delay (a delay>255 is split into a sequence of delays)
			{
				DigiKeyboard.delay(mod);
			}
			else DigiKeyboard.sendKeyStroke(key,mod);
		}
		i--;
		DigiKeyboard.delay(%d); //wait %d milliseconds before next loop iteration

	}
	else if (blink)
	{
		digitalWrite(0, HIGH);   // turn the LED on (HIGH is the voltage level)
		digitalWrite(1, HIGH);
		delay(100);               // wait for a second
		digitalWrite(0, LOW);    // turn the LED off by making the voltage LOW
		digitalWrite(1, LOW);
		delay(100);               // wait for a second
	}
''' % (loop_delay, loop_delay)

	tail = '''}\n'''
	l = len(payload)
	hex_values = [str(hex(ord(payload[c]))) for c in range(l)]
	declare = "#define DUCK_LEN " + str(l) + "\nconst PROGMEM uint8_t duckraw [DUCK_LEN] = {\n\t"
	declare += ", ".join(hex_values) + "\n};\nint i = %d; //how many times the payload should run (-1 for endless loop)\n" % loop_count
	if blink:
		declare += "bool blink=true;\n"
	else:
		declare += "bool blink=false;\n"

	return head + declare + init + body + tail


def main():
	parser = argparse.ArgumentParser(
		prog="duck2spark",
		description="Converts payload created by DuckEncoder to sourcefile for DigiSpark Sketch"
	)
	parser.add_argument("-i", "--input", required=True,
		help="Input File (Payload encoded with DuckEncoder)")
	parser.add_argument("-o", "--output",
		help="Output File for Sketch, if omitted stdout is used")
	parser.add_argument("-l", "--loopcount", type=int, default=1,
		help="Loop count (1=single run (default), -1=endless run, 3=3 runs etc.)")
	parser.add_argument("-f", "--initdelay", type=int, default=1000,
		help="Delay in milliseconds before initial payload run (default 1000)")
	parser.add_argument("-r", "--repeatdelay", type=int, default=5000,
		help="Delay in milliseconds between loop runs (default 5000)")
	parser.add_argument("-n", "--noblink", action="store_true",
		help="Don't blink status LED after finish of payload execution")
	parser.epilog = ("Remark: In order to use DEAD KEYS (f.e. ^ and ` on German keyboard layout) "
		"a SPACE should be appended in the ducky script (f.e. \"STRING ^ working deadkey\").")

	args = parser.parse_args()

	with _safe_open(args.input, "rb") as f:
		payload = f.read()

	result = generate_source(
		payload,
		init_delay=args.initdelay,
		loop_count=args.loopcount,
		loop_delay=args.repeatdelay,
		blink=not args.noblink
	)

	if args.output is None:
		print(result)
	else:
		safe_ofile = os.path.join(os.path.realpath(os.getcwd()), os.path.basename(args.output))
		with _safe_open(safe_ofile, "w") as f:
			f.write(result)
			print("Binary2script Complete..... [ OK ]")


if __name__ == "__main__":
	main()
